# index:
#    path: /
#    controller: App\Controller\DefaultController::index

demo9:
  path: /demo9
  controller: App\Controller\TestController::demo9

demo13:
  path: /demo13/{num}
  controller: App\Controller\TestController::demo13
  requirements:
    num: '\d+'

exo3:
  path: /exos/exo3
  controller: App\Controller\ExoController::exo3

exo4:
  path: /exos/exo4
  controller: App\Controller\ExoController::exo4