doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
            custom:
                url: '%env(resolve:CUSTOM_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        # default_entity_manager: default
        # entity_managers:
        #     default:
        #         connection: default
        #         mappings:
        #             App:
        #                 is_bundle: false
        #                 type: annotation
        #                 dir: '%kernel.project_dir%/src/Entity'
        #                 prefix: 'App\Entity'
        #                 alias: App
            # custom:
            #     connection: custom
            #     mappings:
            #         Custom:
            #             is_bundle: false
            #             type: annotation
            #             dir: '%kernel.project_dir%/src/Entity/Custom'
            #             prefix: 'App\Entity\Custom'
            #             alias: Custom
